site_name: Emlid
theme: readthedocs
site_favicon: favicon.ico
repo_url: https://github.com/emlid
pages:
- ['index.md', 'Introduction']
- ['Navio-APM/power-up-navio-plus.md', 'Navio APM', 'Power up Navio+']
- ['Navio-APM/power-up-navio.md', 'Navio APM', 'Power up Navio']
- ['Navio-APM/installation-and-running.md', 'Navio APM']
- ['Navio-APM/building-from-sources.md', 'Navio APM']
- ['Navio-dev/AHRS.md', 'Navio for developers']
- ['Navio-dev/rtklib.md', 'Navio for developers', 'Navio Raw RTKLib']
- ['Navio-dev/using-default-raspbian.md', 'Navio for developers', 'Using default Raspbian']
- ['RT-Linux/real-time-kernel.md', 'Real-time Linux']
- ['RTKLIB/rtklib-base-setup.md', 'RTK with NEO6-T']
- ['RTKLIB/RTKGPS+.md', 'RTK with NEO6-T']
- ['Downloads.md', 'Downloads', 'Downloads']

