site_name: Emlid
theme: readthedocs
site_favicon: favicon.ico
repo_url: https://github.com/emlid
pages:
- ['index.md', 'Introduction']
- ['Navio-APM/installation-and-running.md', 'Navio APM']
- ['Navio-APM/building-from-sources.md', 'Navio APM']
- ['RT-Linux/real-time-kernel.md', 'Real-time Linux']
- ['RTKLIB/rtklib-base-setup.md', 'RTK with NEO6-T']
- ['Navio-dev/getting-started.md', 'Navio for developers']


