site_name: Emlid
theme: docstheme
site_favicon: favicon.ico
repo_url: https://github.com/emlid/navio-docs
pages:
- Introduction : 'index.md'
- Navio APM:
  - 'Hardware setup Navio+': 'Navio-APM/hardware-setup-navio-plus.md'
  - 'Hardware setup Navio': 'Navio-APM/hardware-setup-navio.md'
  - 'Configuring Raspberry Pi': 'Navio-APM/configuring-raspberry-pi.md'
  - 'APM installation and running' : 'Navio-APM/installation-and-running.md'
  - 'Video Streaming': 'Navio-APM/video-streaming.md'
  - 'Building from sources': 'Navio-APM/building-from-sources.md'
- Downloads:
  - 'Real-time Linux for RPi1': 'Downloads/Real-time-Linux-RPi1.md'
  - 'Real-time Linux for RPi2' : 'Downloads/Real-time-Linux-RPi2.md'
  - 'APM binaries': 'Downloads/APM-binaries.md'
  - 'Windows IoT': 'Downloads/Windows-IoT.md'
- Navio for developers:
  - '9DOF IMU': 'Navio-dev/mpu9250-imu.md'
  - 'AHRS' : 'Navio-dev/AHRS.md'
  - 'Barometer' : 'Navio-dev/ms5611-barometer.md'
  - 'GPS' : 'Navio-dev/read-gps-data.md'
  - 'U-center GPS' : 'Navio-dev/GPS-ucenter.md'
  - 'Servos and RGB LED' : 'Navio-dev/servo-and-rgb-led.md'
  - 'PPM RC input' : 'Navio-dev/rc-input.md'
  - 'ADC' : 'Navio-dev/ads1115-adc.md'
  - 'FRAM' : 'Navio-dev/mb85r-fram.md'
  - 'Navio Raw RTKLib' : 'Navio-dev/rtklib.md'
  - 'Using default Raspbian' : 'Navio-dev/using-default-raspbian.md'
  - 'Datasheets' : 'Navio-dev/datasheets.md'
  - 'Windows IoT': 'Navio-dev/Windows-IoT.md'
- RTK with NEO6-T:
  - 'Rtklib base setup' : 'RTKLIB/rtklib-base-setup.md'
  - 'Rtklib rover setup' : 'RTKLIB/rtklib-rover-setup.md'
  - 'RTKGPS+' : 'RTKLIB/RTKGPS+.md'
