site_name: Emlid
theme: readthedocs
site_favicon: favicon.ico
repo_url: https://github.com/emlid
pages:
- ['index.md', 'Introduction']
- ['Navio-APM/power-up-navio-plus.md', 'Navio APM', 'Power up Navio+']
- ['Navio-APM/hardware-setup-navio-plus.md', 'Navio APM', 'Hardware setup Navio+']
- ['Navio-APM/power-up-navio.md', 'Navio APM', 'Power up Navio']
- ['Navio-APM/hardware-setup-navio.md', 'Navio APM', 'Hardware setup Navio']
- ['Navio-APM/configuring-raspberry-pi.md', 'Navio APM', 'Configuring Raspberry Pi']
- ['Navio-APM/installation-and-running.md', 'Navio APM']
- ['Navio-APM/building-from-sources.md', 'Navio APM']
- ['Navio-dev/mpu9250-imu.md', 'Navio for developers', '9DOF IMU']
- ['Navio-dev/AHRS.md', 'Navio for developers']
- ['Navio-dev/ms5611-barometer.md', 'Navio for developers', 'Barometer']
- ['Navio-dev/read-gps-data.md', 'Navio for developers', 'GPS']
- ['Navio-dev/GPS-ucenter.md', 'Navio for developers', 'U-center GPS']
- ['Navio-dev/servo-and-rgb-led.md', 'Navio for developers', 'Servos and RGB LED']
- ['Navio-dev/rc-input.md', 'Navio for developers', 'PPM RC input']
- ['Navio-dev/ads1115-adc.md', 'Navio for developers', 'ADC']
- ['Navio-dev/mb85r-fram.md', 'Navio for developers', 'FRAM']
- ['Navio-dev/rtklib.md', 'Navio for developers', 'Navio Raw RTKLib']
- ['Navio-dev/using-default-raspbian.md', 'Navio for developers', 'Using default Raspbian']
- ['Navio-dev/datasheets.md', 'Navio for developers', 'Datasheets']
- ['real-time-linux/raspberry-real-time-kernel.md', 'Real-time Linux', 'Raspberry Pi A+/B+']
- ['RTKLIB/rtklib-base-setup.md', 'RTK with NEO6-T']
- ['RTKLIB/rtklib-rover-setup.md', 'RTK with NEO6-T']
- ['RTKLIB/RTKGPS+.md', 'RTK with NEO6-T']
- ['Downloads/Real-time-Linux.md', 'Downloads', 'Real-time Linux']
- ['Downloads/APM-binaries.md', 'Downloads', 'APM binaries']

